<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="cache-control" content="no-cache"/>
    <meta http-equiv="expires" content="0"/>
    <meta http-equiv="pragma" content="no-cache"/>
    <script src="http://code.jquery.com/jquery-1.11.3.min.js"></script>
    <link rel="stylesheet" href="../css/style.css"/>
  </head>
  <body>
  	<div id="root" name="index.phtml">
    
    <form data-ajax="false" id="formular" method="post" action="">
       <div data-role="fieldcontain">
           <fieldset id="field">
            <input type="text" name="subject" id="subject" placeholder="subject">
            <textarea type="text" name="object" id="object" placeholder="object" rows="25"></textarea>
            <input type="submit" id="submit" value="absenden">
           </fieldset>
       </div>
   </form>
    <script src="../js/createComplaint.js"></script>
  </body>
</html>


