<link rel="stylesheet" href="../css/style.css"/>
<div data-role="main" class="ui-content">
   <h1><?php echo $this->vars['text']; ?></h1>
   <form data-ajax="false" id="loginformular" method="post" action="dispatchViews">
       <div data-role="fieldcontain">
           <fieldset>
               <label for="benutzername">Benutzername</label>
               <input type="text" name="user" id="benutzername" focus>
               <label for="kennwort">Kennwort</label>
               <input type="password" name="password" id="kennwort">
               <input type="submit" value="Anmelden">
           </fieldset>
       </div>
   </form>
 </div>

